### PR TITLE
Updated packages and swift-syntax to 600.0.0

### PR DESCRIPTION
**Pull request by atifdev10**

### CODE REVIEW

**Comment by atifdev10** [comment]
All tests pass except for one, which is just indentation.

**Comment by stackotter** [comment]
Hi, thanks for these changes! If you remove the extra spaces on lines 225, 228, 231, and 234 of `Tests/MacroToolkitTests/MacroToolkitTests.swift` to fix the broken test then I'll be happy to merge. Swift Syntax must've fixed whatever was originally causing the code to generate with that weird spacing.

**Comment by atifdev10** [comment]
@stackotter all tests pass now

**Comment by stackotter** [comment]
Awesome, thanks again for helping keep MacroToolkit up to date!

**Pull request merged**
